{
  "identifier": "dixons1985",
  "assetSequences": [
    {
      "packageIdentifier": "dixons1985",
      "index": 0,
      "assetType": "seadragon/dzi",
      "assetCount": 6,
      "supportsSearch": false,
      "rootSection": {
        "title": "Dixons Christmas 1985",
        "sectionType": "Monograph",        
        "assets": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31
        ]
      },
      "assets": [
        {
          "identifier": "dixons01",
          "order": 1,
          "orderLabel": "1",
          "width": 2474,
          "height": 2922,
          "dziUri": "/dz/01/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/01/thumb.jpg"
        },        
        {
          "identifier": "dixons02",
          "order": 2,
          "orderLabel": "2",
          "width": 2474,
          "height": 2947,
          "dziUri": "/dz/02/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/02/thumb.jpg"
        },        
        {
          "identifier": "dixons03",
          "order": 3,
          "orderLabel": "3",
          "width": 2462,
          "height": 2922,
          "dziUri": "/dz/03/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/03/thumb.jpg"
        },        
        {
          "identifier": "dixons04",
          "order": 4,
          "orderLabel": "4",
          "width": 2462,
          "height": 2934,
          "dziUri": "/dz/04/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/04/thumb.jpg"
        },        
        {
          "identifier": "dixons05",
          "order": 5,
          "orderLabel": "5",
          "width": 2474,
          "height": 2922,
          "dziUri": "/dz/05/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/05/thumb.jpg"
        },        
        {
          "identifier": "dixons06",
          "order": 6,
          "orderLabel": "6",
          "width": 2452,
          "height": 2929,
          "dziUri": "/dz/06/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/06/thumb.jpg"
        },        
        {
          "identifier": "dixons07",
          "order": 7,
          "orderLabel": "7",
          "width": 2474,
          "height": 2934,
          "dziUri": "/dz/07/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/07/thumb.jpg"
        },        
        {
          "identifier": "dixons08",
          "order": 8,
          "orderLabel": "8",
          "width": 2451,
          "height": 2930,
          "dziUri": "/dz/08/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/08/thumb.jpg"
        },        
        {
          "identifier": "dixons09",
          "order": 9,
          "orderLabel": "9",
          "width": 2474,
          "height": 2947,
          "dziUri": "/dz/09/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/09/thumb.jpg"
        },        
        {
          "identifier": "dixons10",
          "order": 10,
          "orderLabel": "10",
          "width": 2446,
          "height": 2928,
          "dziUri": "/dz/10/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/10/thumb.jpg"
        },        
        {
          "identifier": "dixons11",
          "order": 11,
          "orderLabel": "11",
          "width": 2481,
          "height": 2926,
          "dziUri": "/dz/11/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/11/thumb.jpg"
        },        
        {
          "identifier": "dixons12",
          "order": 12,
          "orderLabel": "12",
          "width": 2434,
          "height": 2905,
          "dziUri": "/dz/12/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/12/thumb.jpg"
        },        
        {
          "identifier": "dixons13",
          "order": 13,
          "orderLabel": "13",
          "width": 2450,
          "height": 2913,
          "dziUri": "/dz/13/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/13/thumb.jpg"
        },        
        {
          "identifier": "dixons14",
          "order": 14,
          "orderLabel": "14",
          "width": 2431,
          "height": 2927,
          "dziUri": "/dz/14/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/14/thumb.jpg"
        },        
        {
          "identifier": "dixons15",
          "order": 15,
          "orderLabel": "15",
          "width": 2444,
          "height": 2922,
          "dziUri": "/dz/15/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/15/thumb.jpg"
        },        
        {
          "identifier": "dixons16",
          "order": 16,
          "orderLabel": "16",
          "width": 2447,
          "height": 2917,
          "dziUri": "/dz/16/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/16/thumb.jpg"
        },        
        {
          "identifier": "dixons17",
          "order": 17,
          "orderLabel": "17",
          "width": 2440,
          "height": 2913,
          "dziUri": "/dz/17/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/17/thumb.jpg"
        },        
        {
          "identifier": "dixons18",
          "order": 18,
          "orderLabel": "18",
          "width": 2427,
          "height": 2912,
          "dziUri": "/dz/18/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/18/thumb.jpg"
        },        
        {
          "identifier": "dixons19",
          "order": 19,
          "orderLabel": "19",
          "width": 2450,
          "height": 2905,
          "dziUri": "/dz/19/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/19/thumb.jpg"
        },        
        {
          "identifier": "dixons20",
          "order": 20,
          "orderLabel": "20",
          "width": 2412,
          "height": 2918,
          "dziUri": "/dz/20/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/20/thumb.jpg"
        },        
        {
          "identifier": "dixons21",
          "order": 21,
          "orderLabel": "21",
          "width": 2444,
          "height": 2919,
          "dziUri": "/dz/21/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/21/thumb.jpg"
        },        
        {
          "identifier": "dixons22",
          "order": 22,
          "orderLabel": "22",
          "width": 2424,
          "height": 2905,
          "dziUri": "/dz/22/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/22/thumb.jpg"
        },        
        {
          "identifier": "dixons23",
          "order": 23,
          "orderLabel": "23",
          "width": 2458,
          "height": 2915,
          "dziUri": "/dz/23/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/23/thumb.jpg"
        },        
        {
          "identifier": "dixons24",
          "order": 24,
          "orderLabel": "24",
          "width": 2399,
          "height": 2907,
          "dziUri": "/dz/24/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/24/thumb.jpg"
        },        
        {
          "identifier": "dixons25",
          "order": 25,
          "orderLabel": "25",
          "width": 2452,
          "height": 2907,
          "dziUri": "/dz/25/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/25/thumb.jpg"
        },        
        {
          "identifier": "dixons26",
          "order": 26,
          "orderLabel": "26",
          "width": 2414,
          "height": 2907,
          "dziUri": "/dz/26/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/26/thumb.jpg"
        },        
        {
          "identifier": "dixons27",
          "order": 27,
          "orderLabel": "27",
          "width": 2441,
          "height": 2908,
          "dziUri": "/dz/27/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/27/thumb.jpg"
        },        
        {
          "identifier": "dixons28",
          "order": 28,
          "orderLabel": "28",
          "width": 2417,
          "height": 2913,
          "dziUri": "/dz/28/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/28/thumb.jpg"
        },        
        {
          "identifier": "dixons29",
          "order": 29,
          "orderLabel": "29",
          "width": 2466,
          "height": 2907,
          "dziUri": "/dz/29/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/29/thumb.jpg"
        },        
        {
          "identifier": "dixons30",
          "order": 30,
          "orderLabel": "30",
          "width": 2437,
          "height": 2905,
          "dziUri": "/dz/30/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/30/thumb.jpg"
        },        
        {
          "identifier": "dixons31",
          "order": 31,
          "orderLabel": "31",
          "width": 2449,
          "height": 2904,
          "dziUri": "/dz/31/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/31/thumb.jpg"
        },        
        {
          "identifier": "dixons32",
          "order": 32,
          "orderLabel": "32",
          "width": 2442,
          "height": 2916,
          "dziUri": "/dz/32/dzc_output.xml",
          "fileUri": "",
          "navigatorPath": "",
          "thumbnailPath": "/dz/32/thumb.jpg"
        }
      ]
    }
  ]
}